<?php

/**
 * @file
 * Support for tweets as media entities.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_browser_generic_embed\OverrideHelper as Override;
use Drupal\d324_media_twitter\Plugin\media\Source\D324MediaTwitter;

/**
 * Implements hook_media_source_info_alter().
 */
function d324_media_twitter_media_source_info_alter(array &$sources) {
  $sources['twitter']['input_match'] = [
    'constraint' => 'TweetEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $sources['twitter']['preview'] = TRUE;

  Override::pluginClass($sources['twitter'], D324MediaTwitter::class);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function d324_media_twitter_form_entity_embed_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Only at the embed step.
  if ($form_state->get('step') == 'embed') {

    // Get the entity values and attributes.
    $entity_element = empty($values['attributes']) ? array() : $values['attributes'];
    $entity_element += $form_state->get('entity_element');
    $form_state->set('entity_element', $entity_element);
    $entity = $form_state->get('entity');

    // Get the entity bundle type.
    $bundle_type = $entity->bundle();
    $values = $form_state->getValues();

    if ($bundle_type == "tweet") { 
        // Render the Embed entity.
        $form['entity'] = [
          '#type' => 'item',
          '#markup' => \Drupal::service('renderer')->renderRoot(entity_view($entity, 's06')),
        ];

        if (isset($form['attributes']['data-align'])) {
          unset($form['attributes']['data-align']);
        }

        if (isset($form['attributes']['data-entity-embed-display-settings'])) {
          unset($form['attributes']['data-entity-embed-display-settings']);
        }

        if (isset($form['attributes']['data-caption'])) {
          unset($form['attributes']['data-caption']);
        }

        if (isset($form['attributes']['data-entity-embed-display'])) {
          $form['attributes']['data-entity-embed-display']['#access'] = FALSE;
          $form['attributes']['data-entity-embed-display']['#default_value'] = 'view_mode:media.original';
        }
    }
  }
}
